[graph]
all-features = true
targets = ["x86_64-pc-windows-msvc"]
[advisories]
yanked = "deny"
[licenses]
confidence-threshold = 0.8
allow = ["Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MIT", "MPL-2.0", "Unicode-3.0", "Zlib"]
[bans]
multiple-versions = "warn"
wildcards = "allow"
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
