use clap::{Parser, Subcommand};
use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    GenerateBindings,
    CheckBindings,
    CheckArchitecture,
    CheckProduct,
    Version { semver: String },
}

#[derive(Deserialize)]
struct ProductRegistry {
    product: Product,
    links: Links,
}
#[derive(Deserialize)]
struct Product {
    name: String,
    version: String,
    identifier: String,
    author: String,
    repository: String,
}
#[derive(Deserialize)]
struct Links {
    releases: String,
    issues: String,
    author: String,
}

fn main() -> ExitCode {
    let root = workspace_root();
    let result = match Cli::parse().command {
        Command::GenerateBindings => generate_bindings(&root),
        Command::CheckBindings => check_bindings(&root),
        Command::CheckArchitecture => check_architecture(&root),
        Command::CheckProduct => check_product(&root),
        Command::Version { semver } => set_version(&root, &semver),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .unwrap()
        .to_path_buf()
}

fn command_names(root: &Path) -> Result<Vec<String>, String> {
    let source = fs::read_to_string(root.join("src-tauri/src/lib.rs")).map_err(display)?;
    let inner = source
        .split_once("generate_handler![")
        .and_then(|(_, rest)| rest.split_once("]"))
        .map(|(inner, _)| inner)
        .ok_or_else(|| "generate_handler! block missing".to_string())?;
    let mut names: Vec<_> = inner
        .split(',')
        .filter_map(|item| item.trim().rsplit("::").next())
        .map(str::trim)
        .filter(|name| {
            !name.is_empty()
                && name
                    .chars()
                    .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_')
        })
        .map(str::to_owned)
        .collect();
    names.sort();
    names.dedup();
    Ok(names)
}

fn bindings_text(root: &Path) -> Result<String, String> {
    let mut output = String::from("// Generated by cargo xtask generate-bindings. Do not edit.\n\nimport { invoke as tauriInvoke } from \"@tauri-apps/api/core\";\n\nexport const COMMANDS = {\n");
    for name in command_names(root)? {
        output.push_str(&format!("  {name}: \"{name}\",\n"));
    }
    output.push_str("} as const;\n\nexport type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];\n\nexport function invokeCommand<T>(command: CommandName, args?: Record<string, unknown>): Promise<T> {\n  return tauriInvoke<T>(command, args);\n}\n");
    Ok(output)
}

fn product(root: &Path) -> Result<ProductRegistry, String> {
    toml::from_str(&fs::read_to_string(root.join("product.toml")).map_err(display)?)
        .map_err(display)
}

fn product_text(root: &Path) -> Result<String, String> {
    let registry = product(root)?;
    let value = serde_json::json!({
        "name": registry.product.name, "version": registry.product.version,
        "identifier": registry.product.identifier, "author": registry.product.author,
        "repository": registry.product.repository, "releases": registry.links.releases,
        "issues": registry.links.issues, "authorUrl": registry.links.author,
    });
    Ok(format!("// Generated by cargo xtask generate-bindings. Do not edit.\nexport const PRODUCT = {} as const;\n", serde_json::to_string_pretty(&value).map_err(display)?))
}

fn generate_bindings(root: &Path) -> Result<(), String> {
    let dir = root.join("frontend/src/generated");
    fs::create_dir_all(&dir).map_err(display)?;
    fs::write(dir.join("bindings.ts"), bindings_text(root)?).map_err(display)?;
    fs::write(dir.join("product.ts"), product_text(root)?).map_err(display)
}

fn check_bindings(root: &Path) -> Result<(), String> {
    let binding_path = root.join("frontend/src/generated/bindings.ts");
    let product_path = root.join("frontend/src/generated/product.ts");
    if fs::read_to_string(&binding_path).map_err(display)? != bindings_text(root)? {
        return Err(format!("{} is stale", binding_path.display()));
    }
    if fs::read_to_string(&product_path).map_err(display)? != product_text(root)? {
        return Err(format!("{} is stale", product_path.display()));
    }
    Ok(())
}

fn check_architecture(root: &Path) -> Result<(), String> {
    let mut violations = vec![];
    visit(&root.join("frontend/src"), &mut |path| {
        if path
            .components()
            .any(|part| part.as_os_str() == "generated")
        {
            return;
        }
        if !matches!(
            path.extension().and_then(|ext| ext.to_str()),
            Some("ts" | "svelte")
        ) {
            return;
        }
        if let Ok(raw) = fs::read_to_string(path) {
            for (index, line) in raw.lines().enumerate() {
                if line.contains("@tauri-apps/api/core")
                    || line.contains("invoke(\"")
                    || line.contains("invoke('")
                    || line.contains("invokeCommand(\"")
                    || line.contains("invokeCommand('")
                {
                    violations.push(format!(
                        "{}:{} raw Tauri command transport",
                        path.display(),
                        index + 1
                    ));
                }
            }
        }
    })?;
    if violations.is_empty() {
        Ok(())
    } else {
        Err(violations.join("\n"))
    }
}

fn check_product(root: &Path) -> Result<(), String> {
    let expected = product(root)?.product.version;
    for path in [
        "Cargo.toml",
        "src-tauri/tauri.conf.json",
        "package.json",
        "frontend/package.json",
        "product.toml",
    ] {
        let raw = fs::read_to_string(root.join(path)).map_err(display)?;
        if !raw.contains(&format!("\"{expected}\"")) {
            return Err(format!("{path} version differs from {expected}"));
        }
    }
    Ok(())
}

fn set_version(root: &Path, version: &str) -> Result<(), String> {
    let parts: Vec<_> = version.split('.').collect();
    if parts.len() != 3 || parts.iter().any(|part| part.parse::<u64>().is_err()) {
        return Err(format!("invalid SemVer: {version}"));
    }
    replace_first(root.join("Cargo.toml"), "version = \"", version)?;
    replace_first(root.join("product.toml"), "version = \"", version)?;
    for path in [
        "src-tauri/tauri.conf.json",
        "package.json",
        "frontend/package.json",
    ] {
        replace_json_version(root.join(path), version)?;
    }
    generate_bindings(root)?;
    check_product(root)
}

fn replace_first(path: PathBuf, prefix: &str, value: &str) -> Result<(), String> {
    let mut raw = fs::read_to_string(&path).map_err(display)?;
    let start = raw
        .find(prefix)
        .ok_or_else(|| format!("{} lacks version", path.display()))?
        + prefix.len();
    let end = start
        + raw[start..]
            .find('"')
            .ok_or_else(|| "unterminated version".to_string())?;
    raw.replace_range(start..end, value);
    fs::write(path, raw).map_err(display)
}

fn replace_json_version(path: PathBuf, value: &str) -> Result<(), String> {
    let raw = fs::read_to_string(&path).map_err(display)?;
    let old = raw
        .lines()
        .find(|line| line.trim_start().starts_with("\"version\":"))
        .ok_or_else(|| format!("{} lacks version", path.display()))?;
    let indent = old.len() - old.trim_start().len();
    let comma = if old.trim_end().ends_with(',') {
        ","
    } else {
        ""
    };
    let new = format!("{}\"version\": \"{value}\"{comma}", " ".repeat(indent));
    fs::write(path, raw.replacen(old, &new, 1)).map_err(display)
}

fn visit(root: &Path, callback: &mut impl FnMut(&Path)) -> Result<(), String> {
    for entry in fs::read_dir(root).map_err(display)? {
        let path = entry.map_err(display)?.path();
        if path.is_dir() {
            visit(&path, callback)?;
        } else {
            callback(&path);
        }
    }
    Ok(())
}

fn display(error: impl std::fmt::Display) -> String {
    error.to_string()
}
